# Generated by Django 5.0.6 on 2024-08-21 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_useraccount_userprofile'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbookingdata',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booking', to='posts.post'),
        ),
    ]
